### ISSUE TITLE
Heavy Armor Master vs crit

### ISSUE THREAD

**Issue by lovemachine44** [SolastaMods/SolastaUnfinishedBusiness#2150]
Heavy Armor Master feat doesn't seem to reduce anything on critical hits. The message saying the damage was reduced by 3 shows up in text but when viewing the damage there is no reduction. The attack was from the enemy "veteran" who I'm pretty certain doesn't have a magical weapon though I could be wrong since I can't look at his inventory.
The save provided unfortunately is after the attack and not before however there is proof in the text box. Getting a save right before a critical hit could end up taking a while if necessary but please let me know if one like that is needed.
[Save file.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/10367849/Save.file.zip)

**Comment by ThyWoof** [comment]
That other save on piercer was very useful. If you can get something similar? Maybe abuse on feats to get more crit chances?

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/211214829-a1531953-3ae4-4e47-8e2f-1175ba2f467d.png)
did a quick debug. Veterans are getting +3 on their bonus damage. This is before we apply the reduction.

![image](https://user-images.githubusercontent.com/13087646/211214880-c91708c4-494d-4301-80e0-39fc01d4097e.png)
so instead of dice + 3 it only rolled 3.

![image](https://user-images.githubusercontent.com/13087646/211214991-efee1869-c40a-43fe-bb81-163e76a6b24b.png)
so tried to change 3 to 5 damage reduction. Was luck to get a critical.

![image](https://user-images.githubusercontent.com/13087646/211215008-f652ee78-6251-453c-a732-40390090ae69.png)
here we can see both dices rolling and a -2 bonus. 3 -5 == -2.

I believe this is working as expected.

**Comment by lovemachine44** [comment]
Oh that's really interesting. It does appear that it's working as intended then. I didn't realize it subtracted from bonuses but that makes sense. Good testing.
