### ISSUE TITLE
UB crafting recipe for studded leather wont work even with all ingredients in inventory 

### ISSUE THREAD

**Issue by Aelyx93** [SolastaMods/SolastaUnfinishedBusiness#2514]
I've tested with primed and normal studded leather in inventory. Crafting recipe for flame dancing studded, survival and others wont work even with all crafting materials. Again, sorry if i bother you, i just wanna help finding stuff that doesnt work...

**Comment by ThyWoof** [comment]
Please share a screenshot and a save to simplify debugging.

**Comment by ThyWoof** [comment]
This is indeed one of the first mods written for Solasta back in 2021. It's been working since so not sure why it doesn't on your end.

![image](https://user-images.githubusercontent.com/13087646/220002964-11eec330-e468-4654-be08-996e3e341582.png)

![image](https://user-images.githubusercontent.com/13087646/220002976-449f9dd0-0bfe-43e5-99f3-d384a8b4d4f5.png)

![image](https://user-images.githubusercontent.com/13087646/220003028-ca9037f9-99e3-48d4-bd61-1447c132b6df.png)
