### ISSUE TITLE
Dual Flurry + Cleaving Attack + Path Of the Spirits (barbarian) Interactions | Bug?

### ISSUE THREAD

**Issue by gutenhuu** [SolastaMods/SolastaUnfinishedBusiness#3419]
Hey ya; So, I noticed a few weird interactions that I'm not sure if they are bugs or if I'm missing something:

- **"Dual flurry" + Bonus actions**

If my Path of the Spirits Barbarian with dual flurry rages in the first turn attacks and hits twice, he gets the "Dual flurry" text proc, but it cannot make the bonus attack.

The same happens if he uses the "spirit guardian" power as a bonus action

The workaround is to attack and hit twice before using the bonus action, But this way, I lose the extra damage from rage in the first two attacks

- **Cleaving attack + Dual flurry**

If the cleaving attack and dual flurry procs in the same turn, I don't get 2 extra bonus attacks, only 1. The only advantage is that I can attack with the main hand weapon as a bonus action.

I believe the correct interaction was to have 2 extra bonus attacks on top of your normal one.

- **After checking the changelog for version: [1.5.49.1](https://github.com/SolastaMods/SolastaUnfinishedBusiness/releases/tag/1.5.49.1) I noticed this: (but I'm running the most recent version of the mod 1.5.49.3)**

**_fixed Dual Flurry to only grant the extra attack once per turn_**

I only ever got the extra attack once per turn, and I still only get one even after this version; I thought this was the correct way the feat would work as getting 1 extra attack for every 2 hits seems a bit overpowered.

Similar thing with Cleaving attack, would be possible to get more than 1 extra attack if I critical more than once per turn?

I uploaded the save file for reference;

Let me know your thoughts,
Thanks!

[PoI_EoD2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11657212/PoI_EoD2.zip)

**Comment by ThyWoof** [comment]
The issue with Path is by design. These feats grant an extra attack, not an extra action.

I improved Cleaving Attack a bit so it works in a better way now.

1) round start
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/43b854f6-6bd4-4ef8-8ba5-a9156837658b)

2) after killing with my second attack that hit (got dual flurry and cleaving attacks)
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/02e473a4-19fd-423f-8014-9f56cf011a5f)

I'm also trying to improve the interaction of all these feats / features that grant extra attack with action surge. For now this is the best I can do for the reported issue.

**Comment by gutenhuu** [comment]
Thanks for looking into it! Appreciate your support
