### ISSUE TITLE
Shared spell metamagic unavailable when casting Spirit shroud self buff spell 

### ISSUE THREAD

**Issue by DenisFolcher** [SolastaMods/SolastaUnfinishedBusiness#3600]
Hello,

I suppose that spirit shroud spell being a self buff can be used along with the metamagic ; shared spells
Yet when casting spirit shroud, the metamagic option doesnt even appear.

Nb: can be tester with Sylph in the attached save
[015.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11840851/015.zip)

**Comment by Geriboys** [comment]
Same can be said to Shadow Blade as well. It would be nice to give it to a two-weapon fighting martial, but no option is presented for it, not even out of combat.

**Comment by EnderWiggin** [comment]
shadow blade is not a self buff so not sure it is supposed to work like that

**Comment by EnderWiggin** [comment]
and Spirit Shroud is not a self-buff - it is and self-centered AoE, like Spirit Guardians so should not be affected by that metamagic

**Comment by DenisFolcher** [comment]
Correct me if i m wrong but shared spells just affects self spells,
As far as i know, there are no conditions regarding damaging aoe, and
anyway in the case of spirit shroud, the aoe doesnt do any damage, it s a
-2 movement aoe.

Le ven. 23 juin 2023 à 08:59, Andrii Gook ***@***.***> a
écrit :

**Comment by Geriboys** [comment]
> shadow blade is not a self buff so not sure it is supposed to work like that

Well, in official 5e, description says range is self and after checking ingame, it also say self. After you summon it, it will work as a melee weapon attack with a throw property, but the initial casting, where the metamagic should apply, is still self ranged. And i think its the same with Spirit Shroud. But, since i am no programmer, i can't really understand the complications making this ingame.
