### ISSUE TITLE
Flight preventing passage through doors since 1.5.92

### ISSUE THREAD

**Issue by rayndeon** [SolastaMods/SolastaUnfinishedBusiness#3615]
Since the update of Solasta to 1.5.92 and with the release of UB 1.5.92.0, there has been a consistent issue in the single player and multiplayer games I've played with flying characters unable to pass through doors. Characters have had to disable flight in order to be able to pass through various doors. I've attached a save file with a fairy and a winged feral tiefling character unable to pass through a door in the Palace of Ice DLC, an issue that has cropped up repeatedly in my current playthrough since the update. 

[PalaceIceFlightBugExample.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11854584/PalaceIceFlightBugExample.zip)

**Comment by ThyWoof** [comment]
not this mod. we simply reuse a game condition.

**Comment by NeatWolf** [comment]
Can confirm the issue's still there in Palace of Ice, even in an initial area where you're supposed to press 3 plates scattered among the map - and you're very likely going to use fly or similar abilities since the map is a pain to navigate.

It's like the devs forgot to add those "fly tunnels" that they added pretty much everywhere in the game.

In the mentioned map there isn't even a chasm to pass over - there are huge 3mx3m double doors that can't be crossed while flying. 

Probably it needs to be reported to the devs - quite sure they've got a huge backlog of requested fixes.
