### ISSUE TITLE
Paladin Cannot Cast with Deity on Shield

### ISSUE THREAD

**Issue by the1corrupted** [SolastaMods/SolastaUnfinishedBusiness#3925]
For some reason, "Mark Deity" does not remove the free hand requirement for paladin spells.

**Solasta Version:** 1.5.94 (Latest public)
**Mod Version:** 1.5.94.6
**Other Mods Installed:** None

Steps to Reproduce:
Choose race Malakh
Choose Einar as Deity
Wield Warhammer and Shield
**Level 2:** Choose `Shield Expert` Fighting Style
**Level 3:** Choose `Oath of Thunder` and `Angelic Radiance`
Right click Shield and `Mark Deity` - (This is supposed to remove the free hand requirement)
Remove any Divine Focus component from equipped inventory.
Confirm that Somatic Requirements in the Difficulty Settings are set to Full (This will require a free hand)

INCLUDED: 1 Save File and 2 Characters using the same choices as above. XML export of mod settings
[PALADIN SHIELD ISSUE - Save, Character(s), XML Settings.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12327538/PALADIN.SHIELD.ISSUE.-.Save.Character.s.XML.Settings.zip)

**Comment by ThyWoof** [comment]
Paladins and clerics can only casts spells that use the material component with their shield.

Because you can make the somatic component with the same hand you fulfill the material component when casting a spell, you can cast material+somatic spells.

If the spell doesnt need material components, then you cant use the shield hand as the hand to make the somatic component of the spell, because the shield hand is neither free nor being used to add the material components of the spell.

It's working as RAW.
