### ISSUE TITLE
Rogue bonus feat bug at level 10

### ISSUE THREAD

**Issue by NathanNN** [SolastaMods/SolastaUnfinishedBusiness#3939]
94.7 version. If I turn on the option that allow bonus feat at 2, 10, 18 levels. The Rogue for some reason get 2 bonus feats instead of 1 at level 10.
![IMG_3303](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/9156490/de1bdb8f-507b-48f3-a2d0-77d9420588c4)

**Comment by ThyWoof** [comment]
Rogues get one at 10 already. If you enable that option they will stack.

**Comment by NathanNN** [comment]
Hi! According to the Rogue progression at level 10 it should just be 1 ASI, checking the bonus feat at 4, 10, 18 caused Rogue to get 2 feats instead of 1 feat.
![Uploading IMG_3309.jpeg…]()

**Comment by kosocku** [comment]
Aye mate, The Ability Score Improvements will allow you to either add +2 to one of your Ability Scores (or +1 to two different scores).  You can also take a Feat instead of the ASI.  It's an optional rule in 5e.  So Rogues get one at lvl 10.  The mod option also gives one at lvl 10.  Therefore, Rogues will get 2 at lvl 10 if that option is enabled in the Mod.

**Comment by NathanNN** [comment]
oh really? I didn't know that. Seem pretty OP that rogue with that option turn on get 1 ASI and 2 feats. LOL
