### ISSUE TITLE
Psion sorcerer not adding CHA modifier to psychic damage

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4152]
Whenever my 6th level Psion sorcerer casts Shadow Dagger, she is not adding her CHA modifier to the psychic damage, even though her "Mind Sculpt" ability says that she will be adding her CHA modifier to any spell cast that deals psychic damage. 

Save attached.
[Psion.sav.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13060809/Psion.sav.zip)

**Comment by ThyWoof** [comment]
Thanks for save. Fixed in DEV but I won't release anytime soon.

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/59e48ce2-c812-432b-96fe-1999e3989d82)

Replace your DLL with attached.

[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/13061053/SolastaUnfinishedBusiness.zip)

**Comment by Bawookles** [comment]
Thanks for the DLL!
