### ISSUE TITLE
No respec in multiplayer

### ISSUE THREAD

**Issue by charlesewatkins** [SolastaMods/SolastaUnfinishedBusiness#4442]
Sometime in the past few days, respecs in multiplayer games and maps have been disallowed. I can understand that respecs during multiplayer play might lead to problems. But why can't I take the game into single player mode and then do my respec? This had been working well as far as I can tell. Many of my builds call for respecs at some point -- eg. converting a Paladin to a Battle Cleric at level 8. 

In a recent game, my partner had to drop out and I wanted to continue to play solo. He'd flubbed his last level up and I wanted to fix the character, but this is now disallowed. Seems to be due to the campaign being designated as a multiplayer map even though it was being played in solo mode. So what is a multiplayer map? One that has ever been loaded under Multiplayer? Is it then tainted forever?

BTW I'd have like to have read about this change in the Release Notes before I updated to the current level.

Would it be possible to add a switch to control this? Thanks for your consideration.

**Comment by ThyWoof** [comment]
There were no changes at all in RESPEC for a good while now. I believe if you start a save in MP mode it will be tagged as MP forever. If you start in solo mode, and then continue in MP, it won’t happen. Unfortunately it’s been like this since MP was released by TA. I’ll check if I can remove this limitation with a big red sign stating it will break under MP.

**Comment by ThyWoof** [comment]
removed restriction from next release and updated setting option to state it won't work under MP
