### ISSUE TITLE
Tempest's destructive wrath not working with transmuted spell metamagic

### ISSUE THREAD

**Issue by RodrigoMamedeCosta** [SolastaMods/SolastaUnfinishedBusiness#4680]
Tempest's destructive wrath not working with transmuted spell metamagic.

**Comment by HiddenHax** [comment]
That combination cannot work as Destructive Wrath requires thunder or lightning damage.

Channel Divinity: Destructive Wrath
Starting at 2nd level, you can use your Channel Divinity to wield the power of the storm with unchecked ferocity.

When you roll **lightning or thunder damage**, you can use your Channel Divinity to deal maximum damage, instead of rolling.

**Comment by HiddenHax** [comment]
Unless you meant that you wanted to change lightning damage into thunder, or thunder into lightning?

**Comment by RodrigoMamedeCosta** [comment]
No, RAW the transmuted spells can be used for destructive wrath, so you can for example maximize the damage of a thunder-transmuted fireball.

I will provide the save tomorrow, since I don't have one in combat right now.

**Comment by HiddenHax** [comment]
Oh thaaat. Didn't think of that scenario, yes that makes sense. Hopefully the game sequencing can allow allow this scenario.

**Comment by RodrigoMamedeCosta** [comment]
FYI I tested the opposite interaction (destructive wrath on, casting a lightning/thunder spell and then transmuting it into something else) and it didn't maximize it, so the issue is not because it's assuming that it's rolling the original spell type.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/73f73439-630d-4a90-b29b-fbbb36251155)
