### ISSUE TITLE
Plane Touched - Flame Touched

### ISSUE THREAD

**Issue by Hanyo99** [SolastaMods/SolastaUnfinishedBusiness#4759]
Prior to the most recent update the Plane Touched Feat showed the PLane Touched box on the action bar menu for your "once per long rest" cast of the spells it grants. It is no longer showing that, meaning you can't use your once per days granted by the feat.

**Comment by ThyWoof** [comment]
![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/13087646/8c43bff6-b2df-4021-8cbe-95fc36ebfe9c)
without a save I have to use my coding time to test on your behalf. Usually when I do it works.

please open a proper ticket next time with logs and saves. Otherwise nothing I can do.
